#version: '3.8'

services:
  db:
    image: postgres:15
    container_name: odoo_db_local
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=sistemas26#
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    networks:
      - odoo_network

  web:
    image: odoo:17.0
    container_name: odoo_web_local
    depends_on:
      - db
    ports:
      - "8069"
    volumes:
      - odoo_data_local:/var/lib/odoo
      - ./extra-addons:/mnt/extra-addons  # Carpeta para tus módulos personalizados
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=sistemas26#
    networks:
      - odoo_network

  node-exporter:
     image: prom/node-exporter:latest
     container_name: node_exporter_agent
     volumes:
       - /proc:/host/proc:ro
       - /sys:/host/sys:ro
       - /:/rootfs:ro
     command:
       - '--path.procfs=/host/proc'
       - '--path.rootfs=/rootfs'
       - '--path.sysfs=/host/sys'
       - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
     ports:
       - "9100:9100"
     restart: unless-stopped
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    container_name: certbot_ssl
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done'"

  promtail:
     image: grafana/promtail:latest
     container_name: promtail_agent
     volumes:
       - /var/lib/docker/containers:/var/lib/docker/containers:ro # 👈 Lee logs de Docker
       - ./promtail-config.yml:/etc/promtail/config.yml
     command: -config.file=/etc/promtail/config.yml
     restart: unless-stopped

volumes:
  postgres_data_local:
  odoo_data_local:

networks:
  odoo_network:
    driver: bridge
