events { worker_connections 1024; }

http {
    upstream odoo {
        server web:8069;
    }

    # 1. Redirección automática de HTTP (80) a HTTPS (443)
    server {
        listen 80;
        server_name odoo.jgerardogm.lat; # 👈 Reemplaza por tu dominio real

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    # 2. Servidor Seguro HTTPS (443)
    server {
        listen 443 ssl;
        server_name odoo.jgerardogm.lat; # 👈 Reemplaza por tu dominio real

        # Rutas de los certificados que generará Certbot
        ssl_certificate /etc/letsencrypt/live/odoo.jgerardogm.lat/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/odoo.jgerardogm.lat/privkey.pem;

        # Optimización de Seguridad SSL
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # Proxy de peticiones hacia el contenedor de Odoo
        location / {
            proxy_pass http://odoo;
            proxy_set_header X-Forwarded-Host $to_percentage$host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            
            # Evita desconexiones en cargas pesadas o reportes largos
            proxy_read_timeout 720s;
            proxy_connect_timeout 720s;
            proxy_send_timeout 720s;
        }
    }
}
